name: Publish
on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to publish
        required: true
jobs:
  lint:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - run: pod lib lint

  create-release:
    runs-on: ubuntu-latest
    needs: lint
    steps:

    - uses: jungwinter/split@v1
      id: split
      with:
        seperator: /
        msg: ${{ github.ref }}

    - uses: actions/checkout@v2
      with:
        ref: master
        fetch-depth: 0  # zero means “all” (or push fails)

    - name: Update committed versions
      run: |
        ruby -i -pe "sub(/CURRENT_PROJECT_VERSION = [0-9.]+/, 'CURRENT_PROJECT_VERSION = $v')" PromiseKit.xcodeproj/project.pbxproj
        ruby -i -pe "sub(/s.version = '[0-9.]+'/, 's.version = \"$v\"')" PromiseKit.podspec
      env:
        v: ${{ github.event.inputs.version }}
    - run: |
        ! (git diff --quiet)
    - run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git commit -am "PromiseKit $v"
        git push
      env:
        v: ${{ github.event.inputs.version }}

    - uses: softprops/action-gh-release@v1
      id: release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.inputs.version }}
        name: ${{ github.event.inputs.version }}
